### ISSUE TITLE
Kjörstaðir/Kjörskrá - Where do I vote?

### ISSUE THREAD

**Issue by kristjanmik** [kristjanmik/kjosturett-web#12]
We have been working on a lookup service for where to vote. We are tracking changes in the [kjorskra branch](https://github.com/kristjanmik/kjosturett-web/tree/kjorskra)

**Comment by kristjanmik** [comment]
We are mostly done but it still need some design love. This is the current status of the page:
<img width="997" alt="screen shot 2017-10-21 at 10 54 56 am" src="https://user-images.githubusercontent.com/911107/31860768-5be81452-b70f-11e7-8066-8c907339b43d.png">

**Comment by MiniGod** [comment]
I and @andri gave this some love today. PR #21.
