### ISSUE TITLE
Process candidate images

### ISSUE THREAD

**Issue by rthor** [kristjanmik/kjosturett-web#14]
We've got a few hundred images of candidates that we need to crop into 500x500px face images. Does anyone want to take this task? I'm guessing there's an easy solution that won't require manually cropping each image.

The original images should not be changed, we should rather output a new version into `/data/candidates-processed/*`.

Task includes:
- [ ] Crop image, center around face.
- [ ] Resize to 500x500px.
- [ ] Optimize file size.

**Comment by kristjanmik** [comment]
We could use something out of the box like [this](https://docs.imgix.com/apis/url/face-detection) on top of an S3 bucket. We could then just download all the images and store them ourselves

**Comment by axelg12** [comment]
What about using something like: https://github.com/jwagner/smartcrop.js/

**Comment by axelg12** [comment]
I am looking into this

**Comment by kristjanmik** [comment]
@axelg12 we are going with the Imgix approach. @hlodver is on top of it

**Comment by hlodver** [comment]
I set up a simple IMGIX project so now we can fetch the images like this:
https://kjosturett-is.imgix.net/adalsteinn-arason.jpg?fit=facearea&facepad=2.0&w=300&h=300
BW: https://kjosturett-is.imgix.net/adalsteinn-arason.jpg?fit=facearea&facepad=2.0&w=300&h=300&sat=-100 

[IMGIX API Reference](https://docs.imgix.com/apis/url)

**Comment by rthor** [comment]
Awesome! Thanks @hlodver !
