### ISSUE TITLE
Display opening hours of your kjörstaður (polling station)

### ISSUE THREAD

**Issue by daggala** [kristjanmik/kjosturett-web#25]
After providing your SSN to see "Hvar á ég að kjósa?", also opening hours of your kjörstaður (polling station). I'm waiting for a reply from Innaríkisráðuneytið (Home Office) to get access to this data.

**Comment by daggala** [comment]
In the meantime while waiting for access to this data, I could implement it only for people living in Reykjavik where the polling stations are open between 9-22.

**Comment by kristjanmik** [comment]
I know that every sveitastjórn in every constituency announces their own time to vote. I'm not even sure if innanríkisráðuneytið has that info, as they just have a guideline on when to open.

**Comment by daggala** [comment]
They replied my e-mail and will display all the informations about opening hours, on their website kosning.is, tomorrow or Wednesday.

**Comment by kristjanmik** [comment]
@daggala This is super nice! It would be great to implement into as many places as we can

**Comment by daggala** [comment]
They contacted me again and said they will they're trying to finish the list today, if not today, then tomorrow, they will keep me posted.

**Comment by kristjanmik** [comment]
I find it insane that the main voter registry is compiling this list just because of your request. Why was it not already done?

**Comment by daggala** [comment]
They're not doing it only because of my request, but they're kind to keep in touch to let me know the status :) Apparently it's difficult to get replies from every municipality because some of them are not very responsive and they want to show all opening hours at once.
