### ISSUE TITLE
Autoscroll þegar málefni/flokkur er valinn

### ISSUE THREAD

**Issue by benediktvaldez** [kristjanmik/kjosturett-web#46]
Þegar ég reyni að vafra um síðuna og skoða flokka og málefni þá lendi ég í rosalega óþægilegu scrolli (kippist efst á síðuna og smooth scrollar niður til baka á réttan stað) alltaf þegar ég opna nýtt „accordion“ eða section eða hvað sem við viljum kalla það.

![Screen Capture on 2021-08-23 at 21-31-51](https://user-images.githubusercontent.com/1928103/130522525-eb116c2a-e494-49d7-bf5a-a1ba97e8264f.gif)

- Google Chrome Version 92.0.4515.159 (Official Build) (arm64)
- macOS 11.4 – macbook pro 13" M1

**Comment by benediktvaldez** [comment]
Er í smá törn þessa vikuna, en ef þið náið ekki að kíkja á þetta skal ég reyna að gera PR þegar tími gefst

**Comment by rthor** [comment]
Takk fyrir error reportið! Þetta ætti að vera komið í lag.
